### PR TITLE
Testcase1 and Testcase2 added

### PR DESCRIPTION
**Pull request by suchitrachinnakonda**
Hi,

I have added and committed Testcase1 and Testcase2. Please review and approve.

Regards,
Suchitrachinnakonda

### CODE REVIEW

**Comment by suchitracm** [comment]
Hi Suchitra Chinnakonda,

Your code looks good. Please add one more method in Testcase2.

Regards,
Suchitracm

**Comment by suchitrachinnakonda** [comment]
Hi Suchitracm,
I have added another method in Testcase2. Please approve.
Regards,
Suchitra Chinnakonda

**Comment by suchitracm** [comment]
Hi Suchitra Chinnakonda,
Your code looks good. Please go ahead with merge to master.
Regards,
Suchitracm

**Comment by suchitrachinnakonda** [comment]
Hi Suchitracm,
Merging branch to master
Regards,
Suchitra

**Comment by suchitracm** [comment]
Hi Suchitra Chinnakonda,
The code looks good. Please merge to master.
Regards,
Suhitracm

**Pull request merged**
